### PR TITLE
Update to use newer Node JS goodies like class, Promises. Fix some bugs.

### PR DESCRIPTION
**Pull request by dersimn**

### CODE REVIEW

**Comment by skarcha** [comment]
Wow! I suppose you tested it because I can't at the moment. All those changes deserve a 2.0.0 version... :-)

Thanks for your work!

**Comment by skarcha** [comment]
Hello again.

Could you update README about the new use of promises, example directory, etc...?

**Comment by dersimn** [comment]
I'll do some more work on the project next week, then I'll take care of the README file.

Currently the library doesn't automatically reconnect when the according upsd went offline for reboot etc.

**Comment by skarcha** [comment]
Great news! Thank you @dersim!

**Pull request merged**
